import { AcademicClass, StampType } from './models';

export const defaultClasses: AcademicClass[] = [
  {
    id: 'fisica-101-g1',
    name: 'Física para Ingeniería',
    code: 'FIS-101',
    group: 'Grupo 1 (Matutino)',
    schedule: 'Lun, Mié, Vie • 08:00 - 10:00',
    classroom: 'Laboratorio L-204 & Aula A-12',
    description: 'Cinemática, dinámica, termofísica y electromagnetismo aplicada a ingeniería.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'sensores-305-g2',
    name: 'Sensores e Instrumentación',
    code: 'INS-305',
    group: 'Grupo 2 (Intermedio)',
    schedule: 'Mar, Jue • 11:00 - 13:30',
    classroom: 'Laboratorio de Electrónica y Sistemas',
    description: 'Metrología, acondicionamiento de señales y sistemas de adquisición DAQ.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'economia-204-g1',
    name: 'Economía Sostenible',
    code: 'ECO-204',
    group: 'Grupo 1 (Vespertino)',
    schedule: 'Lun, Mié • 14:00 - 16:00',
    classroom: 'Edificio B • Aula Magna 3',
    description: 'Ciclos de vida, evaluación socioeconómica y sustentabilidad industrial.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'energia-402-g1',
    name: 'Pura Energía (Seminario de Proyectos)',
    code: 'ENE-402',
    group: 'Grupo Avanzado',
    schedule: 'Viernes • 11:00 - 15:00',
    classroom: 'Taller de Energías Renovables',
    description: 'Prototipado, investigación y modelado de sistemas energéticos.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
];

export const defaultStampTypes: StampType[] = [
  {
    id: 'sello-agua',
    name: 'Sello de Agua 💧 (Participación, Asistencia y Tareas)',
    description: 'Participación activa, tarea a tiempo, actividad en clase, ejercicios correctos, asistencia o notas de clase.',
    value: 1,
    category: 'participacion',
    icon: 'star',
    color: '#0284C7',
  },
  {
    id: 'sello-tierra',
    name: 'Sello de Tierra 🌱 (Análisis Crítico & Bitácora)',
    description: '5 sellos Agua desbloquean Tierra: Pregunta crítica, debate argumentado, bitácora al corriente o 0 inasistencias.',
    value: 1,
    category: 'excelencia',
    icon: 'shield',
    color: '#16A34A',
  },
  {
    id: 'sello-fuego',
    name: 'Sello de Fuego 🔥 (Desafío del Status Quo & Excelencia)',
    description: '2 sellos Tierra desbloquean Fuego: Desafiar el status quo, 3 prácticas seguidas con 9+ o 2 exámenes con 10.',
    value: 1,
    category: 'laboratorio',
    icon: 'zap',
    color: '#DC2626',
  },
  {
    id: 'sello-aire',
    name: 'Sello de Aire 💨 (Dominio Grupal e Investigación)',
    description: '2 sellos Fuego desbloquean Aire: Resolver un problema/cálculo frente al grupo o investigación de 1 cuartilla.',
    value: 1,
    category: 'tarea',
    icon: 'sparkles',
    color: '#D97706',
  },
  {
    id: 'sello-avatar',
    name: 'Sello de Avatar 🌀 (Maestría Integral)',
    description: '2 sellos Aire dan oportunidad a Avatar: Responder con mínimo 8 un examen sorpresa de 10 preguntas.',
    value: 1,
    category: 'excelencia',
    icon: 'award',
    color: '#7C3AED',
  },
];
