import { AcademicClass, StampType } from './models';

export const defaultClasses: AcademicClass[] = [
  {
    id: 'fisica-101-g1',
    name: 'Física para Ingeniería',
    code: 'FIS-101',
    group: 'Grupo 1 (Matutino)',
    schedule: 'Lun, Mié, Vie • 08:00 - 10:00',
    classroom: 'Laboratorio L-204 & Aula A-12',
    description: 'Cinemática, dinámica, termofísica y electromagnetismo aplicada a ingeniería.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'sensores-305-g2',
    name: 'Sensores e Instrumentación',
    code: 'INS-305',
    group: 'Grupo 2 (Intermedio)',
    schedule: 'Mar, Jue • 11:00 - 13:30',
    classroom: 'Laboratorio de Electrónica y Sistemas',
    description: 'Metrología, acondicionamiento de señales y sistemas de adquisición DAQ.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'economia-204-g1',
    name: 'Economía Sostenible',
    code: 'ECO-204',
    group: 'Grupo 1 (Vespertino)',
    schedule: 'Lun, Mié • 14:00 - 16:00',
    classroom: 'Edificio B • Aula Magna 3',
    description: 'Ciclos de vida, evaluación socioeconómica y sustentabilidad industrial.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
  {
    id: 'energia-402-g1',
    name: 'Pura Energía (Seminario de Proyectos)',
    code: 'ENE-402',
    group: 'Grupo Avanzado',
    schedule: 'Viernes • 11:00 - 15:00',
    classroom: 'Taller de Energías Renovables',
    description: 'Prototipado, investigación y modelado de sistemas energéticos.',
    teacherEmail: 'prof.xochitl.zapata@institucion.edu.mx',
    active: true,
  },
];

export const defaultStampTypes: StampType[] = [
  {
    id: 'sello-participacion-oro',
    name: 'Sello de Participación Activa',
    description: 'Aporte argumentativo clave o resolución de problema en pizarrón.',
    value: 1,
    category: 'participacion',
    icon: 'star',
    color: '#F59E0B',
  },
  {
    id: 'sello-laboratorio-limpio',
    name: 'Sello de Práctica Experimental Completa',
    description: 'Montaje de circuito y mesa de trabajo verificada limpia y en orden.',
    value: 2,
    category: 'laboratorio',
    icon: 'shield',
    color: '#10B981',
  },
  {
    id: 'sello-puntualidad-entrega',
    name: 'Sello de Entrega Impecable',
    description: 'Entrega previa al límite de tiempo con cálculos analíticos justificados.',
    value: 1,
    category: 'tarea',
    icon: 'clock',
    color: '#3B82F6',
  },
  {
    id: 'sello-excelencia-tecnica',
    name: 'Sello de Excelencia Técnica y Rigor',
    description: 'Superación destacada del objetivo de la práctica o proyecto.',
    value: 3,
    category: 'excelencia',
    icon: 'sparkles',
    color: '#8B5CF6',
  },
];
