'use client';
import { useState } from 'react';
import { doc, setDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import { AcademicClass } from '@/lib/firebase/models';
export default function ClassEditor({ item, open, onSave }: { item: AcademicClass; open: boolean; onSave: (message: string) => void }) {
  const [draft, setDraft] = useState(item); const [editing, setEditing] = useState(false); const field = 'rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900';
  const save = async () => { try { await setDoc(doc(db, 'classes', item.id), { ...draft, name: draft.name.trim(), code: draft.code.trim().toUpperCase(), group: draft.group.trim(), schedule: draft.schedule.trim(), updatedAt: new Date().toISOString() }, { merge: true }); setEditing(false); onSave('Clase actualizada.'); } catch { onSave('No se pudo actualizar la clase.'); } };
  return <div className="rounded-2xl border border-slate-200 p-4">{editing ? <div className="grid gap-2 sm:grid-cols-2"><input className={field} value={draft.name} onChange={event => setDraft(current => ({ ...current, name: event.target.value }))} placeholder="Nombre" /><input className={field} value={draft.code} onChange={event => setDraft(current => ({ ...current, code: event.target.value }))} placeholder="Clave" /><input className={field} value={draft.group} onChange={event => setDraft(current => ({ ...current, group: event.target.value }))} placeholder="Grupo" /><input className={field} value={draft.schedule} onChange={event => setDraft(current => ({ ...current, schedule: event.target.value }))} placeholder="Horario" /><input className={`${field} sm:col-span-2`} value={draft.classroom} onChange={event => setDraft(current => ({ ...current, classroom: event.target.value }))} placeholder="Aula" /><div className="flex gap-2 sm:col-span-2"><button type="button" onClick={() => void save()} className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">Guardar cambios</button><button type="button" onClick={() => { setDraft(item); setEditing(false); }} className="rounded-lg border px-3 py-2 text-sm">Cancelar</button></div></div> : <><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{item.name} · {item.group}</h3><p className="text-sm text-slate-500">{item.code} · {item.schedule}</p><p className="text-xs text-slate-500">{item.classroom || 'Aula no asignada'}</p></div><button type="button" onClick={() => setEditing(true)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">Editar clase</button></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={item.active} onChange={event => void setDoc(doc(db, 'classes', item.id), { active: event.target.checked }, { merge: true })} /> Clase activa</label><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={open} onChange={event => void setDoc(doc(db, 'shopSettings', item.id), { open: event.target.checked, updatedAt: new Date().toISOString() }, { merge: true })} /> Tienda abierta para esta clase</label></>}</div>;
}
